### ISSUE TITLE
Asking detail

### ISSUE THREAD

**Issue by LezardValeth97** [onboarding92/deepHealthProjectISIC2019#1]
In [23]: why did you set trainble of layer to false?
And also for the reason to define top_3_accuracy and top_2_accuracy?

Thank you

**Comment by onboarding92** [comment]
**for layer in model.layers[:-134]:
    layer.trainable = False**
Because I need to choose how many layers we actually want to be trained.
Here we are freezing the weights of all layers except the last 23 layers in the new model.
The last 23 layers of the model will be trained. 
For top_2 and top_3 there aren't a reason, you can use every metrics you want. Only i tried with other metrics and it doesn't work well.
Thank you very much for your question.
I hope i answer you.
do not hesitate to ask me

**Comment by LezardValeth97** [comment]
Can I ask again about some information I get quite confused about it!
Pardon me if I lack infomation about the dataset, but inside the column "lesion_id", what does it duplicate that you define a function to find it, also for the define find_val_row, too!

Thank you once again for taking your time answer my question!
